tags:
- name: matching
  description: Matching API

paths:
  /matching:
# [POST] matching
    post:
      tags:
      - matching
      summary: Find Matches (Order x Transactions)
      parameters:
      - name: body
        in: body
        description: transactions and orders
        required: true
        schema:
          $ref: '#/definitions/matching'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  matching:
    type: object
    required:
        - orders
        - transactions
    properties:
      orders:
        type: array
        description: list of orders
        items:
          type: object
          properties:
            customerName:
              type: string
            type:
              type: string
            orderId:
              type: string
            date:
              type: string
            product:
              type: string
            price:
              type: number
      transactions:
        type: array
        description: list of orders
        items:
          type: object
          properties:
            customerName:
              type: string
            type:
              type: string
            orderId:
              type: string
            date:
              type: string
            product:
              type: string
            price:
              type: number
            transactionType:
              type: string
            transactionDate:
              type: string
            transactionAmount:
              type: number

schemes:
 - https
 - http
